Загрузим данные

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/alexsadny/ml-course-homeworks/main/hw02_analysis_of_dataset/ev_battery_qc_data_2026_kaggle.csv"
df = pd.read_csv(url)

df.head()

,Cell_ID,Batch_ID,Production_Line,Shift,Supplier,Ambient_Temp_C,Anode_Overhang_mm,Electrolyte_Volume_ml,Internal_Resistance_mOhm,Capacity_mAh,Retention_50Cycle_Pct,Defect_Type,Inspector_Comment,QC_Grade
0,CELL-004920,BTH-0001,Line_3,Evening,ChemCorp,20.76,0.108,14.81,14.01,4980.0,97.79,Poor Retention,NaN,Scrap
1,CELL-014782,BTH-0001,Line_1,Night,ChemCorp,22.38,0.126,14.96,14.70,4989.0,97.35,NaN,NaN,Grade A
2,CELL-019348,BTH-0001,Line_2,Night,LithioMat,20.18,0.135,14.97,13.80,5032.0,96.77,NaN,Routine visual inspection passed.,Grade A
3,CELL-008537,BTH-0001,Line_2,Morning,VoltIndustries,24.30,0.162,14.84,14.65,5042.0,95.88,NaN,NaN,Grade A
4,CELL-010539,BTH-0001,Line_1,Evening,VoltIndustries,22.22,0.130,14.89,15.04,4943.0,97.74,High Internal Resistance,NaN,Grade A

In [8]:
df.tail()

,Cell_ID,Batch_ID,Production_Line,Shift,Supplier,Ambient_Temp_C,Anode_Overhang_mm,Electrolyte_Volume_ml,Internal_Resistance_mOhm,Capacity_mAh,Retention_50Cycle_Pct,Defect_Type,Inspector_Comment,QC_Grade
19995,CELL-009308,BTH-0499,Line_1,Night,VoltIndustries,20.31,0.129,14.98,14.99,4997.0,96.58,NaN,NaN,Grade A
19996,CELL-011250,BTH-0499,Line_3,Evening,VoltIndustries,21.52,0.119,14.95,14.50,5031.0,97.17,NaN,NaN,Grade B
19997,CELL-003841,BTH-0499,Line_2,Morning,ChemCorp,24.40,0.106,15.05,13.82,4993.0,97.34,NaN,NaN,Scrap
19998,CELL-000715,BTH-0499,Line_1,Evening,VoltIndustries,23.87,0.151,15.06,15.28,4970.0,97.09,High Internal Resistance,NaN,Grade B
19999,CELL-005509,BTH-0499,Line_2,Morning,ChemCorp,24.07,0.112,14.98,14.61,5014.0,95.80,NaN,NaN,Scrap

Узнаем информацию о матрице

In [4]:
df.shape

(20000, 14)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Cell_ID                   20000 non-null  str
 1   Batch_ID                  20000 non-null  str
 2   Production_Line           20000 non-null  str
 3   Shift                     20000 non-null  str
 4   Supplier                  20000 non-null  str
 5   Ambient_Temp_C            19400 non-null  float64
 6   Anode_Overhang_mm         20000 non-null  float64
 7   Electrolyte_Volume_ml     20000 non-null  float64
 8   Internal_Resistance_mOhm  20000 non-null  float64
 9   Capacity_mAh              20000 non-null  float64
 10  Retention_50Cycle_Pct     20000 non-null  float64
 11  Defect_Type               3501 non-null   str
 12  Inspector_Comment         1667 non-null   str
 13  QC_Grade                  20000 non-null  str
dtypes: float64(6), str(8)
memory usage: 2.1 MB

In [6]:
df.describe()

,Ambient_Temp_C,Anode_Overhang_mm,Electrolyte_Volume_ml,Internal_Resistance_mOhm,Capacity_mAh,Retention_50Cycle_Pct
count,19400.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,23.157409,0.137498,14.979050,14.280926,4988.398450,96.801533
std,1.890930,0.020991,0.119464,0.705987,48.205605,1.170866
min,16.260000,0.057000,14.430000,11.900000,4576.000000,90.210000
25%,21.860000,0.123000,14.910000,13.790000,4971.000000,96.350000
50%,23.250000,0.138000,14.990000,14.200000,4995.000000,96.940000
75%,24.490000,0.152000,15.060000,14.680000,5017.000000,97.510000
max,29.790000,0.219000,15.370000,17.640000,5120.000000,100.840000

In [9]:
df.describe(include="object")

/var/folders/5d/1sd4b2bs3cj9zfqd1jd4w4n40000gn/T/ipykernel_97851/702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Cell_ID,Batch_ID,Production_Line,Shift,Supplier,Defect_Type,Inspector_Comment,QC_Grade
count,20000,20000,20000,20000,20000,3501,1667,20000
unique,20000,499,3,3,3,6,7,3
top,CELL-004920,BTH-0273,Line_1,Evening,ChemCorp,High Internal Resistance,Standard calibration OK.,Grade A
freq,1,63,8038,6768,9908,2837,311,13193

In [10]:
df.isnull().sum()

Cell_ID                         0
Batch_ID                        0
Production_Line                 0
Shift                           0
Supplier                        0
Ambient_Temp_C                600
Anode_Overhang_mm               0
Electrolyte_Volume_ml           0
Internal_Resistance_mOhm        0
Capacity_mAh                    0
Retention_50Cycle_Pct           0
Defect_Type                 16499
Inspector_Comment           18333
QC_Grade                        0
dtype: int64

Отсутствие объектов

#### Проверим тип входящих данный

In [11]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Length: 20000, dtype: bool

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.dtypes

Cell_ID                         str
Batch_ID                        str
Production_Line                 str
Shift                           str
Supplier                        str
Ambient_Temp_C              float64
Anode_Overhang_mm           float64
Electrolyte_Volume_ml       float64
Internal_Resistance_mOhm    float64
Capacity_mAh                float64
Retention_50Cycle_Pct       float64
Defect_Type                     str
Inspector_Comment               str
QC_Grade                        str
dtype: object

Данные читаются правильно, повторов нет

In [14]:
df.isnull().any(axis=1).sum()

np.int64(19575)

Перейдем к обработке пропусков

In [18]:
cols = ["Inspector_Comment", "Defect_Type"]
missing = df[cols].isnull().sum()
missing_pct = df[cols].isnull().mean() * 100
pd.DataFrame({"missing": missing, "pct_missing": missing_pct})

                   missing  pct_missing
Inspector_Comment    18333       91.665
Defect_Type          16499       82.495

Создаем бинарный признак наличия комментария инспектора. Это может быть информативно, так как комментарии чаще появляются при обнаружении проблем в процессе контроля качества.

In [19]:
df["has_comment"] = df["Inspector_Comment"].notna().astype(int)
# Пропущенные текстовые значения заменяем пустой строкой,
# чтобы избежать ошибок при дальнейшем анализе текста (NLP).
df["Inspector_Comment"] = df["Inspector_Comment"].fillna("")

In [20]:
df.head()

,Cell_ID,Batch_ID,Production_Line,Shift,Supplier,Ambient_Temp_C,Anode_Overhang_mm,Electrolyte_Volume_ml,Internal_Resistance_mOhm,Capacity_mAh,Retention_50Cycle_Pct,Defect_Type,Inspector_Comment,QC_Grade,has_comment
0,CELL-004920,BTH-0001,Line_3,Evening,ChemCorp,20.76,0.108,14.81,14.01,4980.0,97.79,Poor Retention,,Scrap,0
1,CELL-014782,BTH-0001,Line_1,Night,ChemCorp,22.38,0.126,14.96,14.70,4989.0,97.35,NaN,,Grade A,0
2,CELL-019348,BTH-0001,Line_2,Night,LithioMat,20.18,0.135,14.97,13.80,5032.0,96.77,NaN,Routine visual inspection passed.,Grade A,1
3,CELL-008537,BTH-0001,Line_2,Morning,VoltIndustries,24.30,0.162,14.84,14.65,5042.0,95.88,NaN,,Grade A,0
4,CELL-010539,BTH-0001,Line_1,Evening,VoltIndustries,22.22,0.130,14.89,15.04,4943.0,97.74,High Internal Resistance,,Grade A,0